// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Static$UiLibrary = require("./Static.bs.js");
var Reaction$UiLibrary = require("./Reaction.bs.js");
var BlockLibrary$UiLibrary = require("./BlockLibrary.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function $less$unknown$unknown$great(b1, b2) {
  return BlockLibrary$UiLibrary.Block2[/* combine */2](b1, b2);
}

function $less$pipe$pipe$great(b1, b2) {
  return BlockLibrary$UiLibrary.Block2[/* either */3](b1, b2);
}

var block2 = BlockLibrary$UiLibrary.Block2[/* mapValue */1]((function () {
        return /* () */0;
      }), BlockLibrary$UiLibrary.Block2[/* mapInit */0]((function () {
            return /* tuple */[
                    /* () */0,
                    /* () */0
                  ];
          }), BlockLibrary$UiLibrary.Block2[/* combine */2](BlockLibrary$UiLibrary.Button[/* block */4], BlockLibrary$UiLibrary.Button[/* block */4])));

var block3 = BlockLibrary$UiLibrary.Block2[/* mapValue */1]((function () {
        return /* () */0;
      }), BlockLibrary$UiLibrary.Block2[/* mapInit */0]((function () {
            return /* Left */Block.__(0, [/* () */0]);
          }), BlockLibrary$UiLibrary.Block2[/* either */3](BlockLibrary$UiLibrary.Button[/* block */4], BlockLibrary$UiLibrary.Button[/* block */4])));

var block4 = BlockLibrary$UiLibrary.Block2[/* mapValue */1]((function () {
        return /* () */0;
      }), BlockLibrary$UiLibrary.Block2[/* mapInit */0]((function () {
            return /* tuple */[
                    /* () */0,
                    4
                  ];
          }), Reaction$UiLibrary.mkBlock2((function (param) {
                if (param[0].tag) {
                  throw [
                        Caml_builtin_exceptions.match_failure,
                        [
                          "Main.ml",
                          22,
                          6
                        ]
                      ];
                } else {
                  var match = param[1][/* events */2];
                  if (match && !match[1]) {
                    return /* :: */[
                            /* Right */Block.__(1, [/* ReInit */Block.__(0, [param[2][/* value */1] + 1 | 0])]),
                            /* [] */0
                          ];
                  } else {
                    return /* [] */0;
                  }
                }
              }), /* tuple */[
              BlockLibrary$UiLibrary.Button[/* block */4],
              Static$UiLibrary.block
            ])));

function runApp(onModelChanged) {
  return BlockLibrary$UiLibrary.run(block4, onModelChanged);
}

var $$static = Static$UiLibrary.block;

exports.$less$unknown$unknown$great = $less$unknown$unknown$great;
exports.$less$pipe$pipe$great = $less$pipe$pipe$great;
exports.block2 = block2;
exports.block3 = block3;
exports.$$static = $$static;
exports.block4 = block4;
exports.runApp = runApp;
/* block2 Not a pure module */
