// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Block2$UiLibrary = require("./Block2.bs.js");

var $less$unknown$unknown$great = Block2$UiLibrary.combine;

var $less$pipe$pipe$great = Block2$UiLibrary.either;

exports.$less$unknown$unknown$great = $less$unknown$unknown$great;
exports.$less$pipe$pipe$great = $less$pipe$pipe$great;
/* No side effect */
