// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function run(block, onModelChanged) {
  var start = function (initialState) {
    var state = [initialState];
    var dispatch = function (action) {
      var result = Curry._2(block[/* handle */1], state[0], action);
      state[0] = result[/* newState */0];
      return Curry._1(onModelChanged, Curry._2(block[/* viewModel */2], state[0], dispatch));
    };
    return dispatch;
  };
  var initialResult = Curry._1(block[/* initialize */0], /* () */0);
  var initialState = initialResult[/* newState */0];
  var dispatch = start(initialResult[/* newState */0]);
  return Curry._2(block[/* viewModel */2], initialState, dispatch);
}

exports.run = run;
/* No side effect */
