// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function initialize(position) {
  return /* record */[
          /* newState : record */[
            /* isSliding : false */0,
            /* position */position
          ],
          /* events : [] */0
        ];
}

function handle(state, action) {
  if (typeof action === "number") {
    if (action !== 0) {
      return /* record */[
              /* newState : record */[
                /* isSliding : false */0,
                /* position */state[/* position */1]
              ],
              /* events : [] */0
            ];
    } else {
      return /* record */[
              /* newState : record */[
                /* isSliding : true */1,
                /* position */state[/* position */1]
              ],
              /* events : [] */0
            ];
    }
  } else {
    return /* record */[
            /* newState : record */[
              /* isSliding : true */1,
              /* position */action[0]
            ],
            /* events : [] */0
          ];
  }
}

function viewModel(state, dispatch) {
  return /* record */[
          /* isSliding */state[/* isSliding */0],
          /* position */state[/* position */1],
          /* onStart */(function () {
              return Curry._1(dispatch, /* StartSliding */0);
            }),
          /* onMove */(function (p) {
              return Curry._1(dispatch, /* MoveSlider */[p]);
            }),
          /* onStop */(function () {
              return Curry._1(dispatch, /* StopSliding */1);
            })
        ];
}

function getValue(state) {
  return state[/* position */1];
}

var block = /* record */[
  /* initialize */initialize,
  /* handle */handle,
  /* viewModel */viewModel,
  /* getValue */getValue
];

exports.block = block;
/* No side effect */
