// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


function initialize(init) {
  return /* record */[
          /* newState */init,
          /* events : [] */0
        ];
}

function handle(state, _) {
  return /* record */[
          /* newState */state,
          /* events : [] */0
        ];
}

function viewModel(state, _) {
  return state;
}

function block_003(x) {
  return x;
}

var block = /* record */[
  /* initialize */initialize,
  /* handle */handle,
  /* viewModel */viewModel,
  block_003
];

exports.block = block;
/* No side effect */
